//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVienApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaPM { get; set; }
        public Nullable<int> MaTL { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
